---
name: macOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start tmate session (detached, early)
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      - name: Install Homebrew dependencies
        run: |
          brew install libtool automake autoconf pkg-config

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - name: Init and install opam packages
        run: |
          opam init -y
          opam switch create 5.3.0
          eval $(opam env)
          opam install . --deps-only -y --confirm-level=unsafe-yes

      - name: Build project
        run: |
          eval $(opam env)
          which opam
          dune build
          dune exec -- bin/main.exe
