---
name: macOS Build
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        macos-version: [macos-13, macos-14, macos-15]

    runs-on: ${{ matrix.macos-version }}
    timeout-minutes: 60

    name: Build on ${{ matrix.macos-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      - name: Install Homebrew dependencies
        run: |
          brew install libtool automake autoconf pkg-config

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - name: Install opam packages
        run: |
          eval $(opam env)
          opam install . --deps-only -y --confirm-level=unsafe-yes

      - name: Build and Run
        run: |
          eval $(opam env)
          which opam
          dune build
          dune exec -- bin/main.exe

      - name: Patch executable
        run: |
          eval $(opam env)
          ./scripts/patch-macos-executable.sh

      - name: Upload bundled binary
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.macos-version }}
          path: dist/
