---
name: macOS Test
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        macos-version: [macos-13, macos-14, macos-15]

    runs-on: ${{ matrix.macos-version }}
    timeout-minutes: 60
    name: Test on ${{ matrix.macos-version }}

    steps:
      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
