---
name: macOS Test
on:
  workflow_dispatch:

jobs:
  test-macos-14:
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: Start tmate session (detached, early)
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

  test-macos-15:
    runs-on: macos-15
    timeout-minutes: 60

    steps:
      - name: Start tmate session (detached, early)
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
