---
name: macOS Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 60

    steps:
      - name: Start tmate session (detached, early)
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
